In [1]:
#pip install numpy
import numpy as np

In [11]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
np.zeros([5,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.zeros((1))

array([0.])

In [8]:
np.zeros((5,7,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [9]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(4,20) #[4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [22]:
arreglo_de_pares = np.arange(0,20,2)

In [21]:
np.arange(-12,1,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [24]:
print(arreglo_de_pares.size)
print(len(arreglo_de_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [26]:
arreglo_de_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [27]:
arreglo_de_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [46]:
arreglo = np.arange(24)
arreglo.reshape(2,3,4)
arreglo.reshape(6,4)
arreglo.reshape(2,2,6)
arreglo.reshape(8,3)
arreglo.reshape(4,2,3)
arreglo.reshape(3,2,2,2)
arreglo.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [47]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [48]:
#suma
a + b

array([15, 15, 15])

In [49]:
#resta
a - b

array([5, 5, 5])

In [50]:
#multiplicacion
a * b

array([50, 50, 50])

In [51]:
# divisiones
a / b

array([2., 2., 2.])

In [65]:
arreglo_3 = np.arange(12,21,0.5)
arreglo_4 = np.arange(-8,1,0.5)

In [76]:
arreglo_3.reshape(3,3,2) + arreglo_4.reshape(3,3,2)

array([[[ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.]],

       [[10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.]]])

In [77]:
arreglo_3.reshape(3,3,2) * arreglo_4.reshape(3,3,2)

array([[[-96.  , -93.75],
        [-91.  , -87.75],
        [-84.  , -79.75]],

       [[-75.  , -69.75],
        [-64.  , -57.75],
        [-51.  , -43.75]],

       [[-36.  , -27.75],
        [-19.  ,  -9.75],
        [  0.  ,  10.25]]])

In [78]:
arreglo_3.reshape(3,3,2) - arreglo_4.reshape(3,3,2)

array([[[20., 20.],
        [20., 20.],
        [20., 20.]],

       [[20., 20.],
        [20., 20.],
        [20., 20.]],

       [[20., 20.],
        [20., 20.],
        [20., 20.]]])

In [79]:
arreglo_4.reshape(3,3,2) / arreglo_3.reshape(3,3,2)

array([[[-0.66666667, -0.6       ],
        [-0.53846154, -0.48148148],
        [-0.42857143, -0.37931034]],

       [[-0.33333333, -0.29032258],
        [-0.25      , -0.21212121],
        [-0.17647059, -0.14285714]],

       [[-0.11111111, -0.08108108],
        [-0.05263158, -0.02564103],
        [ 0.        ,  0.02439024]]])

In [71]:
# mod
a % b

array([0, 0, 0], dtype=int32)

In [80]:
arreglo_4.reshape(3,3,2) % arreglo_3.reshape(3,3,2)

array([[[ 4. ,  5. ],
        [ 6. ,  7. ],
        [ 8. ,  9. ]],

       [[10. , 11. ],
        [12. , 13. ],
        [14. , 15. ]],

       [[16. , 17. ],
        [18. , 19. ],
        [ 0. ,  0.5]]])

In [84]:
# multiplicacion por un escalar
print(a * 10)
# sumar
print(a + 7)
# restar
print(a - 2)
# dividir
print(a/2)
#mod 
print(a % 3)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]
[1 1 1]


In [89]:
arreglo_muestra = np.arange(20).reshape(5,2,2)
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [90]:
resp = arreglo_muestra > 5
resp

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [88]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [119]:
resp1 = arreglo_muestra > 6 
resp2= arreglo_muestra < 14
resp3 = arreglo_muestra % 2 == 0
resp = resp1 & resp2 & resp3

In [120]:
arreglo_muestra[resp]

array([ 8, 10, 12])

In [122]:
resp = (arreglo_muestra > 6) & (arreglo_muestra < 14) & (arreglo_muestra % 2 == 0)
arreglo_muestra[resp]

array([ 8, 10, 12])

In [123]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [124]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [125]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [126]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [127]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [128]:
arreglo_doce = np.arange(12)

In [129]:
arreglo_doce.sum()

66

In [130]:
arreglo_doce.min()

0

In [131]:
arreglo_doce.max()

11

In [132]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [133]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [134]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [135]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])