In [1]:
import numpy as np

In [3]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [5]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [8]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [13]:
arreglo_random = np.random.randint(
    10 # enteros + hasta 
)
arreglo_random

2

In [14]:
arreglo_random = np.random.randint(
    -1,# enteros + hasta
    2 # enteros + hasta 
)
arreglo_random #[-1,2[

1

In [15]:
arreglo_random = np.random.randint(
    0,#  minimos
    11, #maximo 
    3 # numero de randomicos 
)
arreglo_random #[0,11[

array([7, 1, 8])

In [16]:
arreglo_random.mean()

5.333333333333333

In [17]:
np.median(arreglo_random)

7.0

In [18]:
np.std(arreglo_random)

3.0912061651652345

In [19]:
np.var(arreglo_random)

9.555555555555555

In [20]:
np.mean(arreglo_random)

5.333333333333333